# Generated by Django 4.2.2 on 2023-06-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbootstrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guid',
            name='time',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ForgotMyPassword',
        ),
    ]
